/*!
 * @test/library1 - v1.0.0
 * Compiled Thu, 09 Nov 2017 03:30:47 UTC
 *
 * pixi-filters is licensed under the MIT License.
 * http://www.opensource.org/licenses/mit-license
 */
"use strict";function unwrapExports(e){return e&&e.__esModule&&Object.prototype.hasOwnProperty.call(e,"default")?e.default:e}function createCommonjsModule(e,o){return o={exports:{}},e(o,o.exports),o.exports}Object.defineProperty(exports,"__esModule",{value:!0});var commonjsGlobal="undefined"!=typeof window?window:"undefined"!=typeof global?global:"undefined"!=typeof self?self:{},_export=createCommonjsModule(function(e,o){var t=commonjsGlobal&&commonjsGlobal.__extends||function(){var e=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(e,o){e.__proto__=o}||function(e,o){for(var t in o)o.hasOwnProperty(t)&&(e[t]=o[t])};return function(o,t){function n(){this.constructor=o}e(o,t),o.prototype=null===t?Object.create(t):(n.prototype=t.prototype,new n)}}();Object.defineProperty(o,"__esModule",{value:!0});var n;!function(e){var o=function(){return function(){}}();e.A=o}(n=o.pepe||(o.pepe={})),function(e){!function(e){var o=function(){function e(){}return e.hello=function(){console.log("HI!")},e}();e.CoreCitizen=o}(e.core||(e.core={}))}(n=o.pepe||(o.pepe={}));var r=n.core.CoreCitizen;!function(e){var o=function(e){function o(){return null!==e&&e.apply(this,arguments)||this}return t(o,e),o}(r);e.B=o}(n=o.pepe||(o.pepe={})),function(e){var o=function(e){function o(){return null!==e&&e.apply(this,arguments)||this}return t(o,e),o}(e.B);e.C=o}(n=o.pepe||(o.pepe={}));!function(e){var o=function(e){function o(){return null!==e&&e.apply(this,arguments)||this}return t(o,e),o}(n.core.CoreCitizen);e.Nope=o}(o.nope||(o.nope={}))}),_export$1=unwrapExports(_export),_export_1=_export.pepe,_export_2=_export.nope;exports.default=_export$1,exports.pepe=_export_1,exports.nope=_export_2;
//# sourceMappingURL=library1.js.map
